### PR TITLE
Require Dart 3.2, update lints

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by mosuem** [comment]
LGTM, just want to land https://github.com/dart-lang/http2/pull/141 first to check for breaking changes w.r.t. the version rev.

**Comment by mosuem** [comment]
> ## PR Health
> ### Breaking changes ⚠️

cc @kevmoo

**Comment by devoncarew** [comment]
It looks like that check is telling us about a parameter type change:

https://github.com/dart-lang/http2/actions/runs/7671365367/job/20909551116?pr=140#step:11:189

**Comment by kevmoo** [comment]
Can we ignore these warnings?

**Review by mosuem — APPROVED** [review]

**Comment by mosuem** [comment]
> > It looks like that check is telling us about a parameter type change:
> > https://github.com/dart-lang/http2/actions/runs/7671365367/job/20909551116?pr=140#step:11:189
> 
> 1. so freakin cool to get this analysis!
> 2. changing from no param type (`dynamic`) to `Object?` for a param should NOT be a breaking change. (Changing the _return_ type from `dynamic` to `Object?` could be breaking.)

fyi @devmil

**Pull request merged**
